"""add_user_utc_offset

Revision ID: da462b50d7e8
Revises: f63fd21f1343
Create Date: 2026-05-29 19:55:07.823193

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da462b50d7e8'
down_revision: str | Sequence[str] | None = 'f63fd21f1343'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('utc_offset', sa.Integer(), nullable=False, server_default='180'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'utc_offset')
    # ### end Alembic commands ###
